k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: true
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: true
    textWrap: true
    showTime: false

