pretty: true
stream: true
show-model-warnings: false
code-theme: "monokai"
model: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
user-input-color: "#94e2d5"
tool-output-color: "#8aadf4"
tool-error-color: "#ed8796"
tool-warning-color: "#f5a97f"
assistant-output-color: "#c6a0f6"
completion-menu-color: "#cad3f5"
completion-menu-bg-color: "#24273a"
completion-menu-current-color: "#cdd6f4"
completion-menu-current-bg-color: "#f4dbd6"
